### ISSUE TITLE
DMX read example - 'isr_handle' undeclared in arduino 2.14

### ISSUE THREAD

**Issue by tresler** [someweisguy/esp_dmx#117]
I have error with example code or if I am just trying include esp_dmx 3.1 library. It's error only for "old" (stable) esp32_arduino 2.14. If I try with esp32_arduino 3.0 alpha 3 it is not problem. 

```
/home/tomi/Arduino/libraries/esp_dmx/src/dmx/hal/timer.c: In function 'dmx_timer_init':
/home/tomi/Arduino/libraries/esp_dmx/src/dmx/hal/timer.c:97:52: error: 'isr_handle' undeclared (first use in this function); did you mean 'intr_handle_t'?
   timer_isr_callback_add(timer->group, timer->idx, isr_handle, isr_context,
                                                    ^~~~~~~~~~
                                                    intr_handle_t
/home/tomi/Arduino/libraries/esp_dmx/src/dmx/hal/timer.c:97:52: note: each undeclared identifier is reported only once for each function it appears in

exit status 1
```

**Comment by someweisguy** [comment]
Thanks for the report and thank you for your patience. 

This appears to be a silly typo on my end. Are you able to make an edit to that file? You will need to navigate to line 97 of `Arduino/libraries/esp_dmx/src/dmx/hal/timer.c`. There is a pair of lines which read:

```
  timer_isr_callback_add(timer->group, timer->idx, isr_handle, isr_context,
                         isr_flags);
```

I believe the argument which is `isr_handle` needs to be replaced with `dmx_timer_isr`. The end result is that the code should instead read:

```
  timer_isr_callback_add(timer->group, timer->idx, dmx_timer_isr, isr_context,
                         isr_flags);
```

I will also write a patch to fix this issue. Let me know if you have any questions!
