### ISSUE TITLE
pin assignment for ESP32 & 485

### ISSUE THREAD

**Issue by nada0302** [someweisguy/esp_dmx#15]
Thanks for nice library.
I tried using example as it is [DMXRead](https://github.com/someweisguy/esp_dmx/tree/release/v1.1/examples/DMXRead)

using Arduino ide & compile is OK.

but cannot detect DMX signal and found cannot go through both following if statement ...

- if (xQueueReceive(queue, &packet, DMX_RX_PACKET_TOUT_TICK)) {
- } else if (dmxIsConnected) {

pin diagram is followed by here 
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/uart.html#circuit-a-collision-detection-circuit

but, is my wire connection wrong ?
![esp32 - max485 dmx wiring](https://user-images.githubusercontent.com/83690645/161434358-fe5fd9c3-8a8b-43d1-929b-159d238cbb20.jpg)

or is there something I should amend on example code ?

**Comment by someweisguy** [comment]
Thanks for the kind words!

These RS485 circuits can be tricky sometimes and you shouldn't need to make any big changes to the example code. Your wiring diagram looks correct to me, but it's been a while since I've had to think about how the wiring in those RS485 breakout boards are supposed to look.

Does your RS485 breakout board require 5v data?

**Comment by nada0302** [comment]
Thanks for comment. I will check in the weekends and update.

**Comment by nada0302** [comment]
I couldn't solve, but I will try later and may come back. Thks,

**Comment by nada0302** [comment]
Finally, I found my mistake.
Wire layout OK. 
Just wrong to use ESP32-WROVER, which is not able to use pin 16&17.
VCC should be better for 3.3V as ESP32 GPIO is by 3.3V basis.

**Comment by someweisguy** [comment]
Ah, that is a good find! I'm going to reopen this so that documentation can be updated, since all the examples use those pins. Hopefully we can prevent confusion in the future.

**Comment by someweisguy** [comment]
I've updated the readme on the `dev` branch. Hopefully, it is helpful for building RS-485 circuits! I'll close this when I've published a new release.

**Comment by nada0302** [comment]
I saw dev branch and it is very clear ! thanks.

**Comment by MnemonicFish** [comment]
ESP32 won't work with that module, it uses 5v logic, a RS3485 runs 3.3v logic. The Youmile RS485 module operates with 3.3v and 5v, works with ESP32 by connecting its VCC to 3.3v not 5v.

https://www.amazon.co.uk/gp/product/B08BZ8274M/ref=ppx_yo_dt_b_asin_title_o04_s00?ie=UTF8&psc=1

**Comment by nada0302** [comment]
I confirmed run by the module, attached on the first photo. (now I use M5 stack core basic for check, which is ESP32-D0WDQ6-V3) , VCC by 3.3V

**Comment by someweisguy** [comment]
v2.0 is released and addresses these issues. Thanks so much!
