### ISSUE TITLE
Is it possible to receive dmx on one uart and copy/write it on another uart ?

### ISSUE THREAD

**Issue by cgiles** [someweisguy/esp_dmx#155]
For my project, I would need to read on one uart and then copy on the other, is it possible, or would it fail ?

**Comment by bensuffolk** [comment]
That will work fine, I do that on one of my projects.

**Comment by TinyuZhao** [comment]
Have the same problem

**Comment by someweisguy** [comment]
As @bensuffolk says, it should work just fine.

I can't recall if this is mentioned in the documentation, but I will take a look and see if there is anything I can clarify! :)
