### ISSUE TITLE
dmx_port when not using SparkFun shield

### ISSUE THREAD

**Issue by erasmudj** [someweisguy/esp_dmx#18]
I am trying to figure out what to do with the dmx_port_t dmxPort = 2; section when I am not using a Sparkfun Shield but a RS-485 MODULE. 
If I remove it I get errors.

**Comment by someweisguy** [comment]
Hopefully I can help! Take a look at the `dev` branch readme. I just recently added a section on how to wire a RS-485 module [here](https://github.com/someweisguy/esp_dmx/tree/dev#wiring-an-rs-485-circuit). 

`dmx_port_t` is a type that tells your ESP32 which UART port to use for DMX. Depending on which ESP32 you have, you can have up to 3 UART ports. If you're familiar with `Serial` in Arduino, it's like choosing `Serial`, `Serial1`, or `Serial2`.

Hope that helps! Let me know if you have any other questions!

**Comment by erasmudj** [comment]
Thank you. Now I understand.
