### ISSUE TITLE
Very weird issue not always sending to max

### ISSUE THREAD

**Issue by ashrafkawasmi** [someweisguy/esp_dmx#4]
hello and thank you for your library

i am struggling 3 days now to make dmx work with esp32

i succeded with esp32 1.0.6 - but not with 2.0

my problem is that it send dmx for 1 second and then stops
if i send another packet on the same bus - then it is correct and all channels work for a secod

i do not know where to search from - i tried almost every ibrary on dmx on the web

very frustrating

**Comment by someweisguy** [comment]
Thank you for the question. Do you mind sharing your code?

**Comment by someweisguy** [comment]
Let me know if you are still having this issue. Otherwise, I will go ahead and close this ticket. Thanks!
