### ISSUE TITLE
Sending broken - single frame only

### ISSUE THREAD

**Issue by netmindz** [someweisguy/esp_dmx#59]
If I try and send data, I'm seeing only the first frame sent then stops. Confirmed the behavior with your example DMXRwite

10:52:08.131 -> Sending DMX 0x01

Then no further output, unless I comment out dmx_send, but then I'm not sending any frames ;)

**Comment by netmindz** [comment]
This is with 2.0.7 of ESP32

**Comment by netmindz** [comment]
What is odd is that it was working last night, might possibly have been on different ESP version, I may have installed a platform update but don't recall what version i was on when it was working sorry

**Comment by someweisguy** [comment]
I've just tested Arduino-ESP32 v2.0.7 with esp_dmx v3.0.2-beta using the DMXWrite example using a clean workspace with new installs of Arduino and esp_dmx. I am not getting any issues. Perhaps there is something misconfigured in your project?

**Comment by netmindz** [comment]
Tried again, same code, same hardware - now it's fine. Odd
