### ISSUE TITLE
DMX512

### ISSUE THREAD

**Issue by Rumpl-X** [someweisguy/esp_dmx#63]
How can I set which DMX port (0 to 512) should be listened to.  the DMX port in line 32 of the example script is probably not the right one which I assumed and therefore got an error.  to make it short I can only read port 1 all other ports don't work.

Yours sincerely,

Johannes Fürst

**Comment by someweisguy** [comment]
Thanks for reaching out!

You can change the port number to either `0`, `1`, or `2` depending on what type of ESP32 you have. Some ESP32s don't have a third DMX port, so they can only use port `0` or `1`. Typically, port `0` is used to transmit data back to the Serial Monitor on your computer so by default you should use either `1` or `2`.

Hope this helps!

**Comment by Rumpl-X** [comment]
sorry i mistold it, where can i set the dmx address for each device, i think that was my question

Am 10. Mai 2023 00:17:35 MESZ schrieb Mitch Weisbrod ***@***.***>:
>Thanks for reaching out!
>
>You can change the port number to either `0`, `1`, or `2` depending on what type of ESP32 you have. Some ESP32s don't have a third DMX port, so they can only use port `0` or `1`. Typically, port `0` is used to transmit data back to the Serial Monitor on your computer so by default you should use either `1` or `2`.
>
>Hope this helps!
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/someweisguy/esp_dmx/issues/63#issuecomment-1540959698
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
Johannes Fürst
Birkkarspitzstr.19
81671 München
Tel.: 089/74664234
Fax.: 089/74664235
Mo.: 0163/6303622

**Comment by Rumpl-X** [comment]
sorry i mistold it, where can i set the dmx address for each device i can only read the adress number one, i think that was my question

**Comment by someweisguy** [comment]
This library offers a few different functions for reading DMX. Firstly, the function `dmx_receive()` can be used to block until a new packet of DMX data is received. It is recommended to call this function before attempting to read data so that you can ensure a new packet of data has actually been received. 

After receiving a new packet of DMX, you can use the function `dmx_read()`, `dmx_read_offset()`, or `dmx_read_slot()` to read DMX data. `dmx_read_slot()` allows you to read a single DMX address by providing the DMX address you want to read. For example:

```c
const dmx_port_t dmx_num = DMX_NUM_1;
const int address = 5;

int value = dmx_read_slot(dmx_num, address);  // Read DMX address 5 into "value"
```

The readme has information on reading DMX [here](https://github.com/someweisguy/esp_dmx#reading-dmx) which may be helpful. If not, let me know if you have any more questions!

**Comment by Rumpl-X** [comment]
Can you Tell me more about the Funktion of "dmx_write_slot()"
Wehren can I set the dmx-address and the dmx-value and for WhatsApp is the return value?
For what I need the "dmx_send()" Funktion I don't know this exactly?
Please send me an codeexample!

When I have finished my work you are interestet about the Sourcecode to test?

**Comment by Rumpl-X** [comment]
I have two integer variable (once for the address and once for the value) are the value of "dmx_write_slot()" compatible?

**Comment by someweisguy** [comment]
> Can you Tell me more about the Funktion of "dmx_write_slot()" 

Sure! This function writes a single slot (or address) of DMX data. For example, if you would like DMX address 5 to be set to value 128, you can use `dmx_write_slot(dmx_num, 5, 128);`. It returns the value that was written to the DMX address or `-1` on error.

> For what I need the "dmx_send()" Funktion I don't know this exactly? Please send me an codeexample!

The `dmx_send()` function is for sending DMX data out to your DMX devices. There are two steps to transmitting DMX data. The first step is to write data. This can be done with functions such as `dmx_write()` or `dmx_write_slot()`. Writing data writes to a buffer stored within the DMX driver. The second step is to send the data. This is done with `dmx_send()`. [Here ](https://github.com/someweisguy/esp_dmx/blob/release/v3.0/examples/DMXWrite/DMXWrite.ino)is an example of writing and sending DMX data.

> When I have finished my work you are interestet about the Sourcecode to test?

Absolutely! I am not sure if I will be able to do much testing, but I would love to see what you are working on! :)

Let me know if that answers your questions!

**Comment by someweisguy** [comment]
> I have two integer variable (once for the address and once for the value) are the value of "dmx_write_slot()" compatible?

Yep! This is correct!

**Comment by Rumpl-X** [comment]
Yes this helps me a lot!!!

I send you the Compleetly sketch:

You can use it to create a dmx radio bridge, which means you send the data from the receiver to the transmitter via WiFi!!!

**Comment by someweisguy** [comment]
I'll close this for now. If you have any other questions or issues, don't hesitate to reach out!
