### ISSUE TITLE
Wont Work

### ISSUE THREAD

**Issue by labrc** [someweisguy/esp_dmx#74]
im trying to compile even the  example proyects, CONFIG_DMX_MAX_PERSONALITIES It's not declared anywhere so it wont compile

Using Arduino IDE on Fedora Linux.

**Comment by someweisguy** [comment]
Thanks for the heads up! This is happening due to how Arduino builds ESP32 projects. I've patched this problem so it should now build properly.

Let me know if you have any other questions or concerns!
