### ISSUE TITLE
dmx_write_slot does not work

### ISSUE THREAD

**Issue by martin3000** [someweisguy/esp_dmx#8]
In function dmx_write_slot, the value is not written to the buffer. Instead, the index is written to the buffer.

**Comment by someweisguy** [comment]
Thanks for letting me know. [Here's the offending line.](https://github.com/someweisguy/esp_dmx/blob/f60d1c894052ce8c6f2ed8b3cf96f27201056363/src/esp_dmx.c#L655) I'm incredibly embarrassed! Fixed in `dev`.

I'll add a read/write slot example code so that I can add it to my list of tests.

**Comment by someweisguy** [comment]
These changes have been merged. Thanks!
