### ISSUE TITLE
Threadsafe-ness of this library

### ISSUE THREAD

**Issue by glanch** [someweisguy/esp_dmx#84]
Hi,
I was wondering whether this library is considered thread-safe, i.e. if the transmission of dmx can be interrupted by scheduler interrupts that enforce pre-emptive scheduling and thus leading to a bad state in transmission. Do I have to take care of this?

Best, glanch

**Comment by someweisguy** [comment]
Thanks for reaching out and I apologize for the delay - I am currently moving across the country so my internet connection is spotty. 

This library is thread-safe. This library uses critical sections where necessary to ensure code isn't pre-empted where it shouldn't be pre-empted. It also uses a mutex to ensure that multiple tasks can't, for example, send two different packets of DMX at the same time. 

If you are working on a product that is interrupt-heavy, you are able to set the interrupt priority of the DMX driver using the `intr_flags` argument in `dmx_driver_install()`.

Hope this helps! Let me know if you have any other questions!

**Comment by glanch** [comment]
That was very insightful, thank you a lot!
