### ISSUE TITLE
Calling dmx_receive with wait_ticks=0 does never return data

### ISSUE THREAD

**Issue by arneboe** [someweisguy/esp_dmx#87]
From my understanding, if I call dmx_receive with `wait_ticks=0` I should receive data when data has been received since the last time I called it. But that never happens. It always returns 0. 
Is this a bug or is my understanding of the code incorrect? :)

**Comment by netmindz** [comment]
See usage: https://github.com/MoonModules/WLED/pull/64

**Comment by someweisguy** [comment]
>From my understanding, if I call dmx_receive with `wait_ticks=0` I should receive data when data has been received since the last time I called it. But that never happens. It always returns 0.

Your understanding is correct! I will investigate further (after I resolve #86 :P).

**Comment by someweisguy** [comment]
Now that #86 appears to be resolved, I've tested the `wait_ticks=0` behavior and it appears to be behaving as intended. 

Are you still seeing any issues with this? I am using the latest commit on `release/v3.1`.

**Comment by arneboe** [comment]
I am no longer seeing the issue on the latest commit on` release/v3.1`
Thanks!
